language: bash
services:
  - docker
branches:
  only:
    - master
script:
  - ./package_charts.sh
  - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.2.4 repo index .
  - git add *.tgz index.yaml
  - git commit -m '[skip travis] Auto Chart Deploy'
  - git remote rm origin
  - git remote add origin https://$GITHUB_TOKEN@github.com/chrisjohnson00/helm-charts.git
  - git push origin HEAD:master
