language: bash
services:
  - docker
branches:
  only:
    - master
script:
  - echo "Start of AWX Proxy Chart"
  - git clone https://$GITHUB_TOKEN@github.com/chrisjohnson00/awx-proxy-chart.git
  - cd awx-proxy-chart
  - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.0.2 lint .
  - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.0.2 package .
  - mv *.tgz ../.
  - cd ..
  - sudo rm -r awx-proxy-chart
  - echo "End of AWX Proxy Chart"
  - echo "Start of Cadvisor Chart"
  - git clone https://$GITHUB_TOKEN@github.com/chrisjohnson00/cadvisor-chart.git
  - cd cadvisor-chart
  - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.0.2 lint .
  - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.0.2 package .
  - mv *.tgz ../.
  - cd ..
  - sudo rm -r cadvisor-chart
  - echo "End of Cadvisor Chart"
  - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.0.2 repo index .
  - git add *.tgz index.yaml
  - git commit -m '[skip travis] Auto Chart Deploy'
  - git remote rm origin
  - git remote add origin https://$GITHUB_TOKEN@github.com/chrisjohnson00/helm-charts.git
  - git push origin HEAD:master
